repos:
  - repo: git://github.com/dnephin/pre-commit-golang
    rev: master
    hooks:
      - id: go-fmt
        stages: [commit]
      - id: go-lint
        stages: [commit]
      - id: go-imports
        stages: [commit]
      - id: golangci-lint
        stages: [commit]
