#!/bin/sh

STAGED_GO_FILES=$(git diff --cached --name-only | grep ".go$")

if [[ "$STAGED_GO_FILES" = "" ]]; then
  exit 0
fi

PASS=true

for FILE in $STAGED_GO_FILES
do
  goimports -w $FILE

  golint "-set_exit_status" $FILE
  if [[ $? == 1 ]]; then
    PASS=false
  fi
done

go vet ./...
if [[ $? != 0 ]]; then
  PASS=false
fi

if ! $PASS; then
  printf "COMMIT FAILED\n"
  exit 1
fi

exit 0